/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZapisDoSkolkyRouteImport } from './routes/zapis-do-skolky'
import { Route as VzdelavaniARozvojRouteImport } from './routes/vzdelavani-a-rozvoj'
import { Route as ProRodiceRouteImport } from './routes/pro-rodice'
import { Route as OSkolceRouteImport } from './routes/o-skolce'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as BarevneTridyRouteImport } from './routes/barevne-tridy'
import { Route as IndexRouteImport } from './routes/index'

const ZapisDoSkolkyRoute = ZapisDoSkolkyRouteImport.update({
  id: '/zapis-do-skolky',
  path: '/zapis-do-skolky',
  getParentRoute: () => rootRouteImport,
} as any)
const VzdelavaniARozvojRoute = VzdelavaniARozvojRouteImport.update({
  id: '/vzdelavani-a-rozvoj',
  path: '/vzdelavani-a-rozvoj',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRodiceRoute = ProRodiceRouteImport.update({
  id: '/pro-rodice',
  path: '/pro-rodice',
  getParentRoute: () => rootRouteImport,
} as any)
const OSkolceRoute = OSkolceRouteImport.update({
  id: '/o-skolce',
  path: '/o-skolce',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const BarevneTridyRoute = BarevneTridyRouteImport.update({
  id: '/barevne-tridy',
  path: '/barevne-tridy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barevne-tridy': typeof BarevneTridyRoute
  '/kontakty': typeof KontaktyRoute
  '/o-skolce': typeof OSkolceRoute
  '/pro-rodice': typeof ProRodiceRoute
  '/vzdelavani-a-rozvoj': typeof VzdelavaniARozvojRoute
  '/zapis-do-skolky': typeof ZapisDoSkolkyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barevne-tridy': typeof BarevneTridyRoute
  '/kontakty': typeof KontaktyRoute
  '/o-skolce': typeof OSkolceRoute
  '/pro-rodice': typeof ProRodiceRoute
  '/vzdelavani-a-rozvoj': typeof VzdelavaniARozvojRoute
  '/zapis-do-skolky': typeof ZapisDoSkolkyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barevne-tridy': typeof BarevneTridyRoute
  '/kontakty': typeof KontaktyRoute
  '/o-skolce': typeof OSkolceRoute
  '/pro-rodice': typeof ProRodiceRoute
  '/vzdelavani-a-rozvoj': typeof VzdelavaniARozvojRoute
  '/zapis-do-skolky': typeof ZapisDoSkolkyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barevne-tridy'
    | '/kontakty'
    | '/o-skolce'
    | '/pro-rodice'
    | '/vzdelavani-a-rozvoj'
    | '/zapis-do-skolky'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barevne-tridy'
    | '/kontakty'
    | '/o-skolce'
    | '/pro-rodice'
    | '/vzdelavani-a-rozvoj'
    | '/zapis-do-skolky'
  id:
    | '__root__'
    | '/'
    | '/barevne-tridy'
    | '/kontakty'
    | '/o-skolce'
    | '/pro-rodice'
    | '/vzdelavani-a-rozvoj'
    | '/zapis-do-skolky'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarevneTridyRoute: typeof BarevneTridyRoute
  KontaktyRoute: typeof KontaktyRoute
  OSkolceRoute: typeof OSkolceRoute
  ProRodiceRoute: typeof ProRodiceRoute
  VzdelavaniARozvojRoute: typeof VzdelavaniARozvojRoute
  ZapisDoSkolkyRoute: typeof ZapisDoSkolkyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zapis-do-skolky': {
      id: '/zapis-do-skolky'
      path: '/zapis-do-skolky'
      fullPath: '/zapis-do-skolky'
      preLoaderRoute: typeof ZapisDoSkolkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vzdelavani-a-rozvoj': {
      id: '/vzdelavani-a-rozvoj'
      path: '/vzdelavani-a-rozvoj'
      fullPath: '/vzdelavani-a-rozvoj'
      preLoaderRoute: typeof VzdelavaniARozvojRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-rodice': {
      id: '/pro-rodice'
      path: '/pro-rodice'
      fullPath: '/pro-rodice'
      preLoaderRoute: typeof ProRodiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-skolce': {
      id: '/o-skolce'
      path: '/o-skolce'
      fullPath: '/o-skolce'
      preLoaderRoute: typeof OSkolceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barevne-tridy': {
      id: '/barevne-tridy'
      path: '/barevne-tridy'
      fullPath: '/barevne-tridy'
      preLoaderRoute: typeof BarevneTridyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarevneTridyRoute: BarevneTridyRoute,
  KontaktyRoute: KontaktyRoute,
  OSkolceRoute: OSkolceRoute,
  ProRodiceRoute: ProRodiceRoute,
  VzdelavaniARozvojRoute: VzdelavaniARozvojRoute,
  ZapisDoSkolkyRoute: ZapisDoSkolkyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
